# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExtrasWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sqlite3
from PyQt5.QtWidgets import QMessageBox
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Extraswindow(object):
    def __init__(self, window, email):
        self.window = QtWidgets.QMainWindow()
        self.emailtxt = email

    def openLogin(self):
        from login import Ui_loginPage
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_loginPage(window="")
        self.ui.setupUi(self.window)
        self.window.show()

    def openCart(self):
        from cart import Ui_Cart
        self.window = QtWidgets.QWidget()
        self.ui = Ui_Cart()
        self.ui.setupUi(self.window)
        self.window.show()

    def openHome(self):
        # Drinkswindow.destroy()
        from foodsWindow import Ui_FoodMenuwindow
        self.window = QtWidgets.QMainWindow()
        self.emailtxt1 = self.user_3.text()
        self.ui = Ui_FoodMenuwindow(window="", email=self.emailtxt1)
        self.ui.setupUi(self.window)
        self.window.show()

    def openDrinks(self):
        # FoodMenuwindow.close()
        from drinksWindow import Ui_Drinkswindow

        self.emailtxt1 = self.user_3.text()

        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Drinkswindow(window="", email=self.emailtxt1)
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, Extraswindow):
        Extraswindow.setObjectName("Extraswindow")
        Extraswindow.resize(900, 650)
        self.centralwidget = QtWidgets.QWidget(Extraswindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 170, 700))
        self.frame.setStyleSheet("background-color: rgb(51, 55, 53);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.drinksbtn_4 = QtWidgets.QPushButton(self.frame)
        self.drinksbtn_4.setGeometry(QtCore.QRect(10, 220, 151, 31))
        self.drinksbtn_4.setStyleSheet("background-color: rgb(154, 154, 154);\n"
"font: 75 14pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Pictures/New/icons8_takeaway_hot_drink_24px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.drinksbtn_4.setIcon(icon)
        self.drinksbtn_4.setIconSize(QtCore.QSize(20, 20))
        self.drinksbtn_4.setObjectName("drinksbtn_4")
        self.Extrasbtn_4 = QtWidgets.QPushButton(self.frame)
        self.Extrasbtn_4.setGeometry(QtCore.QRect(10, 260, 151, 31))
        self.Extrasbtn_4.setStyleSheet("background-color: rgb(154, 154, 154);\n"
"font: 75 14pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Pictures/New/icons8_plus_24px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Extrasbtn_4.setIcon(icon1)
        self.Extrasbtn_4.setIconSize(QtCore.QSize(20, 20))
        self.Extrasbtn_4.setObjectName("Extrasbtn_4")
        self.cartbtn_19 = QtWidgets.QPushButton(self.frame)
        self.cartbtn_19.setGeometry(QtCore.QRect(10, 300, 151, 31))
        self.cartbtn_19.setStyleSheet("background-color: rgb(154, 154, 154);\n"
"font: 75 14pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Pictures/New/icons8_Shopping_Cart_24px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cartbtn_19.setIcon(icon2)
        self.cartbtn_19.setIconSize(QtCore.QSize(20, 20))
        self.cartbtn_19.setObjectName("cartbtn_19")
        self.homebtn_4 = QtWidgets.QPushButton(self.frame)
        self.homebtn_4.setGeometry(QtCore.QRect(10, 180, 151, 31))
        self.homebtn_4.setStyleSheet("background-color: rgb(154, 154, 154);\n"
"font: 75 14pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius: 15px;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Pictures/New/icons8_home_24px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homebtn_4.setIcon(icon3)
        self.homebtn_4.setIconSize(QtCore.QSize(20, 20))
        self.homebtn_4.setObjectName("homebtn_4")
        self.profile2 = QtWidgets.QPushButton(self.frame)
        self.profile2.setGeometry(QtCore.QRect(10, 540, 151, 31))
        self.profile2.setStyleSheet("background-color: rgb(154, 154, 154);\n"
"font: 75 14pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Pictures/New/icons8_user_male_24px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profile2.setIcon(icon4)
        self.profile2.setIconSize(QtCore.QSize(20, 20))
        self.profile2.setObjectName("profile2")
        self.pushButton_15 = QtWidgets.QPushButton(self.frame)
        self.pushButton_15.setGeometry(QtCore.QRect(10, 580, 151, 31))
        self.pushButton_15.setStyleSheet("background-color: rgb(154, 154, 154);\n"
"font: 75 14pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Pictures/New/icons8_logout_rounded_left_24px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_15.setIcon(icon5)
        self.pushButton_15.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_15.setObjectName("pushButton_15")
        self.label_37 = QtWidgets.QLabel(self.frame)
        self.label_37.setGeometry(QtCore.QRect(30, 30, 111, 101))
        self.label_37.setStyleSheet("border-radius: 50px;\n"
"\n"
"")
        self.label_37.setText("")
        self.label_37.setPixmap(QtGui.QPixmap("Pictures/New/circle-cropped.png"))
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.frame_10 = QtWidgets.QFrame(self.centralwidget)
        self.frame_10.setGeometry(QtCore.QRect(180, 10, 711, 641))
        self.frame_10.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_38 = QtWidgets.QLabel(self.frame_10)
        self.label_38.setGeometry(QtCore.QRect(260, -30, 191, 191))
        self.label_38.setText("")
        self.label_38.setPixmap(QtGui.QPixmap("Pictures/New/Logo.png"))
        self.label_38.setScaledContents(True)
        self.label_38.setObjectName("label_38")
        self.label_5 = QtWidgets.QLabel(self.frame_10)
        self.label_5.setGeometry(QtCore.QRect(310, 100, 91, 31))
        self.label_5.setStyleSheet("font: 75 20pt \"Arial\";\n"
"color: rgb(198, 156, 109);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.user_3 = QtWidgets.QLabel(self.frame_10)
        self.user_3.setGeometry(QtCore.QRect(590, 80, 91, 31))
        self.user_3.setStyleSheet("font: 75 20pt \"Arial\";\n"
"color: rgb(198, 156, 109);")
        self.user_3.setText("")
        self.user_3.setAlignment(QtCore.Qt.AlignCenter)
        self.user_3.setObjectName("user_3")
        self.frame_23 = QtWidgets.QFrame(self.frame_10)
        self.frame_23.setGeometry(QtCore.QRect(380, 210, 141, 231))
        self.frame_23.setStyleSheet("background-color: rgb(51, 55, 53);\n"
"broder-radius: 25px;")
        self.frame_23.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setLineWidth(3)
        self.frame_23.setObjectName("frame_23")
        self.label_99 = QtWidgets.QLabel(self.frame_23)
        self.label_99.setGeometry(QtCore.QRect(0, 10, 141, 121))
        self.label_99.setStyleSheet("image: url(:/newPrefix/pexels-valeria-boltneva-1893556.jpg);")
        self.label_99.setText("")
        self.label_99.setObjectName("label_99")
        self.label_100 = QtWidgets.QLabel(self.frame_23)
        self.label_100.setGeometry(QtCore.QRect(20, 140, 101, 16))
        self.label_100.setStyleSheet("font: 12pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.label_100.setAlignment(QtCore.Qt.AlignCenter)
        self.label_100.setObjectName("label_100")
        self.label_101 = QtWidgets.QLabel(self.frame_23)
        self.label_101.setGeometry(QtCore.QRect(20, 160, 101, 16))
        self.label_101.setStyleSheet("font: 10pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.label_101.setAlignment(QtCore.Qt.AlignCenter)
        self.label_101.setObjectName("label_101")
        self.cartbtn_25 = QtWidgets.QPushButton(self.frame_23)
        self.cartbtn_25.setGeometry(QtCore.QRect(70, 190, 61, 31))
        self.cartbtn_25.setStyleSheet("background-color: rgb(220, 166, 88);\n"
"font: 75 12pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.cartbtn_25.setObjectName("cartbtn_25")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.frame_23)
        self.lineEdit_22.setGeometry(QtCore.QRect(10, 190, 51, 31))
        self.lineEdit_22.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"Calibri\";\n"
"border-radius: 15px;")
        self.lineEdit_22.setText("")
        self.lineEdit_22.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.frame_24 = QtWidgets.QFrame(self.frame_10)
        self.frame_24.setGeometry(QtCore.QRect(550, 210, 141, 231))
        self.frame_24.setStyleSheet("background-color: rgb(51, 55, 53);\n"
"broder-radius: 25px;")
        self.frame_24.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setLineWidth(3)
        self.frame_24.setObjectName("frame_24")
        self.label_102 = QtWidgets.QLabel(self.frame_24)
        self.label_102.setGeometry(QtCore.QRect(0, 10, 141, 121))
        self.label_102.setStyleSheet("image: url(:/newPrefix/pexels-alleksana-4451860.jpg);")
        self.label_102.setText("")
        self.label_102.setObjectName("label_102")
        self.label_103 = QtWidgets.QLabel(self.frame_24)
        self.label_103.setGeometry(QtCore.QRect(20, 140, 101, 16))
        self.label_103.setStyleSheet("font: 12pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.label_103.setAlignment(QtCore.Qt.AlignCenter)
        self.label_103.setObjectName("label_103")
        self.label_104 = QtWidgets.QLabel(self.frame_24)
        self.label_104.setGeometry(QtCore.QRect(20, 160, 101, 16))
        self.label_104.setStyleSheet("font: 10pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.label_104.setAlignment(QtCore.Qt.AlignCenter)
        self.label_104.setObjectName("label_104")
        self.cartbtn_26 = QtWidgets.QPushButton(self.frame_24)
        self.cartbtn_26.setGeometry(QtCore.QRect(70, 190, 61, 31))
        self.cartbtn_26.setStyleSheet("background-color: rgb(220, 166, 88);\n"
"font: 75 12pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.cartbtn_26.setObjectName("cartbtn_26")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.frame_24)
        self.lineEdit_23.setGeometry(QtCore.QRect(10, 190, 51, 31))
        self.lineEdit_23.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"Calibri\";\n"
"border-radius: 15px;")
        self.lineEdit_23.setText("")
        self.lineEdit_23.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.frame_19 = QtWidgets.QFrame(self.frame_10)
        self.frame_19.setGeometry(QtCore.QRect(30, 210, 141, 231))
        self.frame_19.setStyleSheet("background-color: rgb(51, 55, 53);\n"
"broder-radius: 25px;")
        self.frame_19.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setLineWidth(3)
        self.frame_19.setObjectName("frame_19")
        self.label_83 = QtWidgets.QLabel(self.frame_19)
        self.label_83.setGeometry(QtCore.QRect(0, 10, 140, 121))
        self.label_83.setStyleSheet("image: url(:/newPrefix/Chopped-Salad-001_1.jpg);")
        self.label_83.setText("")
        self.label_83.setObjectName("label_83")
        self.label_84 = QtWidgets.QLabel(self.frame_19)
        self.label_84.setGeometry(QtCore.QRect(20, 140, 101, 16))
        self.label_84.setStyleSheet("font: 12pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.label_84.setAlignment(QtCore.Qt.AlignCenter)
        self.label_84.setObjectName("label_84")
        self.label_85 = QtWidgets.QLabel(self.frame_19)
        self.label_85.setGeometry(QtCore.QRect(20, 160, 101, 16))
        self.label_85.setStyleSheet("font: 10pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.label_85.setAlignment(QtCore.Qt.AlignCenter)
        self.label_85.setObjectName("label_85")
        self.cartbtn_20 = QtWidgets.QPushButton(self.frame_19)
        self.cartbtn_20.setGeometry(QtCore.QRect(70, 190, 61, 31))
        self.cartbtn_20.setStyleSheet("background-color: rgb(220, 166, 88);\n"
"font: 75 12pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.cartbtn_20.setObjectName("cartbtn_20")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.frame_19)
        self.lineEdit_18.setGeometry(QtCore.QRect(10, 190, 51, 31))
        self.lineEdit_18.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"Calibri\";\n"
"border-radius: 15px;")
        self.lineEdit_18.setText("")
        self.lineEdit_18.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.frame_20 = QtWidgets.QFrame(self.frame_10)
        self.frame_20.setGeometry(QtCore.QRect(210, 210, 141, 231))
        self.frame_20.setStyleSheet("background-color: rgb(51, 55, 53);\n"
"broder-radius: 25px;")
        self.frame_20.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setLineWidth(3)
        self.frame_20.setObjectName("frame_20")
        self.label_89 = QtWidgets.QLabel(self.frame_20)
        self.label_89.setGeometry(QtCore.QRect(0, 10, 140, 121))
        self.label_89.setStyleSheet("image: url(:/newPrefix/easy-microwave-mashed-potatoes-3059678_hero-01-520a91abceb44719ae5a24a179af8645.jpg);")
        self.label_89.setText("")
        self.label_89.setObjectName("label_89")
        self.label_90 = QtWidgets.QLabel(self.frame_20)
        self.label_90.setGeometry(QtCore.QRect(20, 140, 101, 16))
        self.label_90.setStyleSheet("font: 12pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.label_90.setAlignment(QtCore.Qt.AlignCenter)
        self.label_90.setObjectName("label_90")
        self.label_91 = QtWidgets.QLabel(self.frame_20)
        self.label_91.setGeometry(QtCore.QRect(20, 160, 101, 16))
        self.label_91.setStyleSheet("font: 10pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.label_91.setAlignment(QtCore.Qt.AlignCenter)
        self.label_91.setObjectName("label_91")
        self.cartbtn_22 = QtWidgets.QPushButton(self.frame_20)
        self.cartbtn_22.setGeometry(QtCore.QRect(70, 190, 61, 31))
        self.cartbtn_22.setStyleSheet("background-color: rgb(220, 166, 88);\n"
"font: 75 12pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.cartbtn_22.setObjectName("cartbtn_22")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.frame_20)
        self.lineEdit_20.setGeometry(QtCore.QRect(10, 190, 51, 31))
        self.lineEdit_20.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"Calibri\";\n"
"border-radius: 15px;")
        self.lineEdit_20.setText("")
        self.lineEdit_20.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.profile = QtWidgets.QPushButton(self.frame_10)
        self.profile.setGeometry(QtCore.QRect(610, 20, 51, 51))
        self.profile.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"\n"
"\n"
"")
        self.profile.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Pictures/New/icons8_male_user_60px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profile.setIcon(icon6)
        self.profile.setIconSize(QtCore.QSize(120, 120))
        self.profile.setObjectName("profile")
        Extraswindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Extraswindow)
        self.statusbar.setObjectName("statusbar")
        Extraswindow.setStatusBar(self.statusbar)

        self.cartbtn_20.pressed.connect(self.addSaladToCart)
        self.cartbtn_22.pressed.connect(self.addPotatoToCart)
        self.cartbtn_25.pressed.connect(self.addFriesToCart)
        self.cartbtn_26.pressed.connect(self.addSoupToCart)

        self.homebtn_4.pressed.connect(self.openHome)
        self.drinksbtn_4.pressed.connect(self.openDrinks)
        self.cartbtn_19.pressed.connect(self.openCart)
        self.pushButton_15.pressed.connect(self.logout)

        self.retranslateUi(Extraswindow)
        QtCore.QMetaObject.connectSlotsByName(Extraswindow)

    def logout(self):
        msg = QMessageBox()
        msg.setWindowTitle("Info")
        msg.setText("You have been logged out!")
        msg.setIcon(QMessageBox.Information)
        x = msg.exec_()
        self.openLogin()

    def addSaladToCart(self):
        name = self.label_84.text()
        price = 80
        amount = int(self.lineEdit_18.text())
        conn = sqlite3.connect("restaurant.db", isolation_level=None)
        cursor = conn.cursor()
        total = amount * price
        taxed_total = total + (total * 0.21)

        cursor.execute(
            "INSERT INTO `cart` (item_name, quantity, price, total, taxed_total) VALUES (?, ?, ?, ?, ?)",
            (name, str(amount), str(price), str(total), str(taxed_total)))
        conn.commit()

    def addPotatoToCart(self):
        name = self.label_90.text()
        price = 50
        amount = int(self.lineEdit_20.text())
        conn = sqlite3.connect("restaurant.db", isolation_level=None)
        cursor = conn.cursor()
        total = amount * price
        taxed_total = total + (total * 0.21)

        cursor.execute(
            "INSERT INTO `cart` (item_name, quantity, price, total, taxed_total) VALUES (?, ?, ?, ?, ?)",
            (name, str(amount), str(price), str(total), str(taxed_total)))
        conn.commit()

    def addFriesToCart(self):
        name = self.label_100.text()
        price = 50
        amount = int(self.lineEdit_22.text())
        conn = sqlite3.connect("restaurant.db", isolation_level=None)
        cursor = conn.cursor()
        total = amount * price
        taxed_total = total + (total * 0.21)

        cursor.execute(
            "INSERT INTO `cart` (item_name, quantity, price, total, taxed_total) VALUES (?, ?, ?, ?, ?)",
            (name, str(amount), str(price), str(total), str(taxed_total)))
        conn.commit()

    def addSoupToCart(self):
        name = self.label_103.text()
        price = 50
        amount = int(self.lineEdit_23.text())
        conn = sqlite3.connect("restaurant.db", isolation_level=None)
        cursor = conn.cursor()
        total = amount * price
        taxed_total = total + (total * 0.21)

        cursor.execute(
            "INSERT INTO `cart` (item_name, quantity, price, total, taxed_total) VALUES (?, ?, ?, ?, ?)",
            (name, str(amount), str(price), str(total), str(taxed_total)))
        conn.commit()

    def retranslateUi(self, Extraswindow):
        _translate = QtCore.QCoreApplication.translate
        Extraswindow.setWindowTitle(_translate("Extraswindow", "Extras"))
        self.drinksbtn_4.setText(_translate("Extraswindow", "Drinks"))
        self.Extrasbtn_4.setText(_translate("Extraswindow", "Extras"))
        self.cartbtn_19.setText(_translate("Extraswindow", "Cart"))
        self.homebtn_4.setText(_translate("Extraswindow", "Home"))
        self.profile2.setText(_translate("Extraswindow", "Profile"))
        self.pushButton_15.setText(_translate("Extraswindow", "Log out"))
        self.label_5.setText(_translate("Extraswindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Extras</span></p></body></html>"))
        self.label_100.setText(_translate("Extraswindow", "French Fries"))
        self.label_101.setText(_translate("Extraswindow", "50 AFS"))
        self.cartbtn_25.setText(_translate("Extraswindow", "Add"))
        self.lineEdit_22.setPlaceholderText(_translate("Extraswindow", "Amount"))
        self.label_103.setText(_translate("Extraswindow", "Soup"))
        self.label_104.setText(_translate("Extraswindow", "60 AFS"))
        self.cartbtn_26.setText(_translate("Extraswindow", "Add"))
        self.lineEdit_23.setPlaceholderText(_translate("Extraswindow", "Amount"))
        self.label_84.setText(_translate("Extraswindow", "Chopped Salad"))
        self.label_85.setText(_translate("Extraswindow", "80 AFS"))
        self.cartbtn_20.setText(_translate("Extraswindow", "Add"))
        self.lineEdit_18.setPlaceholderText(_translate("Extraswindow", "Amount"))
        self.label_90.setText(_translate("Extraswindow", "Mashed Potato"))
        self.label_91.setText(_translate("Extraswindow", "50 AFS"))
        self.cartbtn_22.setText(_translate("Extraswindow", "Add"))
        self.lineEdit_20.setPlaceholderText(_translate("Extraswindow", "Amount"))
import images


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Extraswindow = QtWidgets.QMainWindow()
    ui = Ui_Extraswindow(window="", email="")
    ui.setupUi(Extraswindow)
    Extraswindow.show()
    sys.exit(app.exec_())
