# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FoodsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sqlite3
from typing import Union

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow


class Ui_FoodMenuwindow(object):
    def __init__(self, window, email):
        self.window = QtWidgets.QMainWindow()
        self.emailtxt = email

    def openCart(self):
        from cart import Ui_Cart
        self.window = QtWidgets.QWidget()
        self.ui = Ui_Cart()
        self.ui.setupUi(self.window)
        self.window.show()

    def openDrinks(self):
        # FoodMenuwindow.close()
        from drinksWindow import Ui_Drinkswindow

        self.emailtxt1 = self.user.text()

        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Drinkswindow(window="", email=self.emailtxt1)
        self.ui.setupUi(self.window)
        self.window.show()

    def openExtras(self):
        # FoodMenuwindow.close()
        from extrasWindow import Ui_Extraswindow

        self.emailtxt1 = self.user.text()

        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Extraswindow(window="", email=self.emailtxt1)
        self.ui.setupUi(self.window)
        self.window.show()


    def openExtras(self):
        # FoodMenuwindow.destroy()
        from extrasWindow import Ui_Extraswindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Extraswindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, FoodMenuwindow):
        FoodMenuwindow.setObjectName("FoodMenuwindow")
        FoodMenuwindow.resize(900, 650)
        FoodMenuwindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(FoodMenuwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 170, 700))
        self.frame.setStyleSheet("background-color: rgb(51, 55, 53);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.drinksbtn = QtWidgets.QPushButton(self.frame)
        self.drinksbtn.setGeometry(QtCore.QRect(10, 220, 151, 31))
        self.drinksbtn.setStyleSheet("background-color: rgb(154, 154, 154);\n"
"font: 75 14pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Pictures/New/icons8_takeaway_hot_drink_24px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.drinksbtn.setIcon(icon)
        self.drinksbtn.setIconSize(QtCore.QSize(20, 20))
        self.drinksbtn.setObjectName("drinksbtn")
        self.extrasBtn = QtWidgets.QPushButton(self.frame)
        self.extrasBtn.setGeometry(QtCore.QRect(10, 260, 151, 31))
        self.extrasBtn.setStyleSheet("background-color: rgb(154, 154, 154);\n"
"font: 75 14pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Pictures/New/icons8_plus_24px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.extrasBtn.setIcon(icon1)
        self.extrasBtn.setIconSize(QtCore.QSize(20, 20))
        self.extrasBtn.setObjectName("extrasBtn")
        self.cartbtn = QtWidgets.QPushButton(self.frame)
        self.cartbtn.setGeometry(QtCore.QRect(10, 300, 151, 31))
        self.cartbtn.setStyleSheet("background-color: rgb(154, 154, 154);\n"
"font: 75 14pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Pictures/New/icons8_Shopping_Cart_24px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cartbtn.setIcon(icon2)
        self.cartbtn.setIconSize(QtCore.QSize(20, 20))
        self.cartbtn.setObjectName("cartbtn")
        self.homebtn = QtWidgets.QPushButton(self.frame)
        self.homebtn.setGeometry(QtCore.QRect(10, 180, 151, 31))
        self.homebtn.setStyleSheet("background-color: rgb(154, 154, 154);\n"
"font: 75 14pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius: 15px;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Pictures/New/icons8_home_24px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homebtn.setIcon(icon3)
        self.homebtn.setIconSize(QtCore.QSize(20, 20))
        self.homebtn.setObjectName("homebtn")
        self.profile2 = QtWidgets.QPushButton(self.frame)
        self.profile2.setGeometry(QtCore.QRect(10, 540, 151, 31))
        self.profile2.setStyleSheet("background-color: rgb(154, 154, 154);\n"
"font: 75 14pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Pictures/New/icons8_user_male_24px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profile2.setIcon(icon4)
        self.profile2.setIconSize(QtCore.QSize(20, 20))
        self.profile2.setObjectName("profile2")
        self.logoutbtn = QtWidgets.QPushButton(self.frame)
        self.logoutbtn.setGeometry(QtCore.QRect(10, 580, 151, 31))
        self.logoutbtn.setStyleSheet("background-color: rgb(154, 154, 154);\n"
"font: 75 14pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Pictures/New/icons8_logout_rounded_left_24px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logoutbtn.setIcon(icon5)
        self.logoutbtn.setIconSize(QtCore.QSize(20, 20))
        self.logoutbtn.setObjectName("logoutbtn")
        self.label_29 = QtWidgets.QLabel(self.frame)
        self.label_29.setGeometry(QtCore.QRect(30, 30, 111, 101))
        self.label_29.setStyleSheet("border-radius: 50px;\n"
"\n"
"")
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap("Pictures/New/circle-cropped.png"))
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.frame_10 = QtWidgets.QFrame(self.centralwidget)
        self.frame_10.setGeometry(QtCore.QRect(180, 10, 711, 641))
        self.frame_10.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_27 = QtWidgets.QLabel(self.frame_10)
        self.label_27.setGeometry(QtCore.QRect(260, -30, 191, 191))
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap("Pictures/New/Logo.png"))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName("label_27")
        self.label_3 = QtWidgets.QLabel(self.frame_10)
        self.label_3.setGeometry(QtCore.QRect(310, 100, 91, 31))
        self.label_3.setStyleSheet("font: 75 20pt \"Arial\";\n"
"color: rgb(198, 156, 109);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.user = QtWidgets.QLabel(self.frame_10)
        self.user.setGeometry(QtCore.QRect(530, 80, 151, 31))
        self.user.setStyleSheet("font: 75 12pt \"Arial\";\n"
"color: rgb(198, 156, 109);")
        self.user.setAlignment(QtCore.Qt.AlignCenter)
        self.user.setObjectName("user")
        self.frame_2 = QtWidgets.QFrame(self.frame_10)
        self.frame_2.setGeometry(QtCore.QRect(20, 140, 141, 231))
        self.frame_2.setStyleSheet("background-color: rgb(51, 55, 53);\n"
"broder-radius: 25px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(3)
        self.frame_2.setObjectName("frame_2")
        self.label_30 = QtWidgets.QLabel(self.frame_2)
        self.label_30.setGeometry(QtCore.QRect(0, 10, 140, 121))
        self.label_30.setStyleSheet("image: url(:/newPrefix/Kabuli-Pulau-Qabel-Polo-I-got-it-from-my-Maman-2-500x500.jpg);")
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.frame_2)
        self.label_31.setGeometry(QtCore.QRect(20, 140, 101, 16))
        self.label_31.setStyleSheet("font: 12pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.frame_2)
        self.label_32.setGeometry(QtCore.QRect(20, 160, 101, 16))
        self.label_32.setStyleSheet("font: 10pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.addQabuli = QtWidgets.QPushButton(self.frame_2)
        self.addQabuli.setGeometry(QtCore.QRect(70, 190, 61, 31))
        self.addQabuli.setStyleSheet("background-color: rgb(220, 166, 88);\n"
"font: 75 12pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.addQabuli.setObjectName("addQabuli")
        self.amountQabuli = QtWidgets.QLineEdit(self.frame_2)
        self.amountQabuli.setGeometry(QtCore.QRect(10, 190, 51, 31))
        self.amountQabuli.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"Calibri\";\n"
"border-radius: 15px;")
        self.amountQabuli.setText("")
        self.amountQabuli.setAlignment(QtCore.Qt.AlignCenter)
        self.amountQabuli.setObjectName("amountQabuli")
        self.frame_3 = QtWidgets.QFrame(self.frame_10)
        self.frame_3.setGeometry(QtCore.QRect(200, 140, 141, 231))
        self.frame_3.setStyleSheet("background-color: rgb(51, 55, 53);\n"
"broder-radius: 25px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(3)
        self.frame_3.setObjectName("frame_3")
        self.label_39 = QtWidgets.QLabel(self.frame_3)
        self.label_39.setGeometry(QtCore.QRect(0, 10, 141, 121))
        self.label_39.setStyleSheet("\n"
"image: url(:/newPrefix/1568143107638.jpeg);")
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.frame_3)
        self.label_40.setGeometry(QtCore.QRect(20, 140, 101, 16))
        self.label_40.setStyleSheet("font: 12pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.frame_3)
        self.label_41.setGeometry(QtCore.QRect(20, 160, 101, 16))
        self.label_41.setStyleSheet("font: 10pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.addBiryani = QtWidgets.QPushButton(self.frame_3)
        self.addBiryani.setGeometry(QtCore.QRect(70, 190, 61, 31))
        self.addBiryani.setStyleSheet("background-color: rgb(220, 166, 88);\n"
"font: 75 12pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.addBiryani.setObjectName("addBiryani")
        self.amountBiryani = QtWidgets.QLineEdit(self.frame_3)
        self.amountBiryani.setGeometry(QtCore.QRect(10, 190, 51, 31))
        self.amountBiryani.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"Calibri\";\n"
"border-radius: 15px;")
        self.amountBiryani.setText("")
        self.amountBiryani.setAlignment(QtCore.Qt.AlignCenter)
        self.amountBiryani.setObjectName("amountBiryani")
        self.frame_4 = QtWidgets.QFrame(self.frame_10)
        self.frame_4.setGeometry(QtCore.QRect(380, 140, 141, 231))
        self.frame_4.setStyleSheet("background-color: rgb(51, 55, 53);\n"
"broder-radius: 25px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setLineWidth(3)
        self.frame_4.setObjectName("frame_4")
        self.label_42 = QtWidgets.QLabel(self.frame_4)
        self.label_42.setGeometry(QtCore.QRect(0, 10, 141, 121))
        self.label_42.setStyleSheet("image: url(:/newPrefix/cooked-white-rice-garnished-with-mint-ceramic-bowl_55883-6830.jpg);")
        self.label_42.setText("")
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.frame_4)
        self.label_43.setGeometry(QtCore.QRect(20, 140, 101, 16))
        self.label_43.setStyleSheet("font: 12pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.frame_4)
        self.label_44.setGeometry(QtCore.QRect(20, 160, 101, 16))
        self.label_44.setStyleSheet("font: 10pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.addRice = QtWidgets.QPushButton(self.frame_4)
        self.addRice.setGeometry(QtCore.QRect(70, 190, 61, 31))
        self.addRice.setStyleSheet("background-color: rgb(220, 166, 88);\n"
"font: 75 12pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.addRice.setObjectName("addRice")
        self.amountRice = QtWidgets.QLineEdit(self.frame_4)
        self.amountRice.setGeometry(QtCore.QRect(10, 190, 51, 31))
        self.amountRice.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"Calibri\";\n"
"border-radius: 15px;")
        self.amountRice.setText("")
        self.amountRice.setAlignment(QtCore.Qt.AlignCenter)
        self.amountRice.setObjectName("amountRice")
        self.frame_5 = QtWidgets.QFrame(self.frame_10)
        self.frame_5.setGeometry(QtCore.QRect(550, 140, 141, 231))
        self.frame_5.setStyleSheet("background-color: rgb(51, 55, 53);\n"
"broder-radius: 25px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setLineWidth(3)
        self.frame_5.setObjectName("frame_5")
        self.label_48 = QtWidgets.QLabel(self.frame_5)
        self.label_48.setGeometry(QtCore.QRect(0, 10, 141, 121))
        self.label_48.setStyleSheet("image: url(:/newPrefix/TMChickenLarge_1024x676.jpg);")
        self.label_48.setText("")
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.frame_5)
        self.label_49.setGeometry(QtCore.QRect(20, 140, 101, 16))
        self.label_49.setStyleSheet("font: 12pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.frame_5)
        self.label_50.setGeometry(QtCore.QRect(20, 160, 101, 16))
        self.label_50.setStyleSheet("font: 10pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.addKebab = QtWidgets.QPushButton(self.frame_5)
        self.addKebab.setGeometry(QtCore.QRect(70, 190, 61, 31))
        self.addKebab.setStyleSheet("background-color: rgb(220, 166, 88);\n"
"font: 75 12pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.addKebab.setObjectName("addKebab")
        self.amountKebab = QtWidgets.QLineEdit(self.frame_5)
        self.amountKebab.setGeometry(QtCore.QRect(10, 190, 51, 31))
        self.amountKebab.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"Calibri\";\n"
"border-radius: 15px;")
        self.amountKebab.setText("")
        self.amountKebab.setAlignment(QtCore.Qt.AlignCenter)
        self.amountKebab.setObjectName("amountKebab")
        self.frame_6 = QtWidgets.QFrame(self.frame_10)
        self.frame_6.setGeometry(QtCore.QRect(20, 380, 141, 231))
        self.frame_6.setStyleSheet("background-color: rgb(51, 55, 53);\n"
"broder-radius: 25px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setLineWidth(3)
        self.frame_6.setObjectName("frame_6")
        self.label_51 = QtWidgets.QLabel(self.frame_6)
        self.label_51.setGeometry(QtCore.QRect(0, 10, 141, 121))
        self.label_51.setStyleSheet("image: url(:/newPrefix/KORMA-1400x919-7b02c527-02dd-4f57-aac0-fdbb1ea2e993-0-1400x919.jpg);")
        self.label_51.setText("")
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.frame_6)
        self.label_52.setGeometry(QtCore.QRect(20, 140, 101, 16))
        self.label_52.setStyleSheet("font: 12pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.frame_6)
        self.label_53.setGeometry(QtCore.QRect(20, 160, 101, 16))
        self.label_53.setStyleSheet("font: 10pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.addQorma = QtWidgets.QPushButton(self.frame_6)
        self.addQorma.setGeometry(QtCore.QRect(70, 190, 61, 31))
        self.addQorma.setStyleSheet("background-color: rgb(220, 166, 88);\n"
"font: 75 12pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.addQorma.setObjectName("addQorma")
        self.amountQorma = QtWidgets.QLineEdit(self.frame_6)
        self.amountQorma.setGeometry(QtCore.QRect(10, 190, 51, 31))
        self.amountQorma.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"Calibri\";\n"
"border-radius: 15px;")
        self.amountQorma.setText("")
        self.amountQorma.setAlignment(QtCore.Qt.AlignCenter)
        self.amountQorma.setObjectName("amountQorma")
        self.frame_7 = QtWidgets.QFrame(self.frame_10)
        self.frame_7.setGeometry(QtCore.QRect(200, 380, 141, 231))
        self.frame_7.setStyleSheet("background-color: rgb(51, 55, 53);\n"
"broder-radius: 25px;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setLineWidth(3)
        self.frame_7.setObjectName("frame_7")
        self.label_54 = QtWidgets.QLabel(self.frame_7)
        self.label_54.setGeometry(QtCore.QRect(0, 10, 141, 121))
        self.label_54.setStyleSheet("image: url(:/newPrefix/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2011__11__italian-meatballs-horiz-c-1800-e83b24e913364fd6b867805335961d65.jpg);")
        self.label_54.setText("")
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.frame_7)
        self.label_55.setGeometry(QtCore.QRect(20, 140, 101, 16))
        self.label_55.setStyleSheet("font: 12pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.frame_7)
        self.label_56.setGeometry(QtCore.QRect(20, 160, 101, 16))
        self.label_56.setStyleSheet("font: 10pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName("label_56")
        self.addMeat = QtWidgets.QPushButton(self.frame_7)
        self.addMeat.setGeometry(QtCore.QRect(70, 190, 61, 31))
        self.addMeat.setStyleSheet("background-color: rgb(220, 166, 88);\n"
"font: 75 12pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.addMeat.setObjectName("addMeat")
        self.amountMeat = QtWidgets.QLineEdit(self.frame_7)
        self.amountMeat.setGeometry(QtCore.QRect(10, 190, 51, 31))
        self.amountMeat.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"Calibri\";\n"
"border-radius: 15px;")
        self.amountMeat.setText("")
        self.amountMeat.setAlignment(QtCore.Qt.AlignCenter)
        self.amountMeat.setObjectName("amountMeat")
        self.frame_8 = QtWidgets.QFrame(self.frame_10)
        self.frame_8.setGeometry(QtCore.QRect(380, 380, 141, 231))
        self.frame_8.setStyleSheet("background-color: rgb(51, 55, 53);\n"
"broder-radius: 25px;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setLineWidth(3)
        self.frame_8.setObjectName("frame_8")
        self.label_57 = QtWidgets.QLabel(self.frame_8)
        self.label_57.setGeometry(QtCore.QRect(0, 10, 141, 121))
        self.label_57.setStyleSheet("image: url(:/newPrefix/pexels-public-domain-pictures-41320.jpg);")
        self.label_57.setText("")
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.frame_8)
        self.label_58.setGeometry(QtCore.QRect(20, 140, 101, 16))
        self.label_58.setStyleSheet("font: 12pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.frame_8)
        self.label_59.setGeometry(QtCore.QRect(20, 160, 101, 16))
        self.label_59.setStyleSheet("font: 10pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setObjectName("label_59")
        self.addSpag = QtWidgets.QPushButton(self.frame_8)
        self.addSpag.setGeometry(QtCore.QRect(70, 190, 61, 31))
        self.addSpag.setStyleSheet("background-color: rgb(220, 166, 88);\n"
"font: 75 12pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.addSpag.setObjectName("addSpag")
        self.amountSpag = QtWidgets.QLineEdit(self.frame_8)
        self.amountSpag.setGeometry(QtCore.QRect(10, 190, 51, 31))
        self.amountSpag.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"Calibri\";\n"
"border-radius: 15px;")
        self.amountSpag.setText("")
        self.amountSpag.setAlignment(QtCore.Qt.AlignCenter)
        self.amountSpag.setObjectName("amountSpag")
        self.frame_9 = QtWidgets.QFrame(self.frame_10)
        self.frame_9.setGeometry(QtCore.QRect(550, 380, 141, 231))
        self.frame_9.setStyleSheet("background-color: rgb(51, 55, 53);\n"
"broder-radius: 25px;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setLineWidth(3)
        self.frame_9.setObjectName("frame_9")
        self.label_60 = QtWidgets.QLabel(self.frame_9)
        self.label_60.setGeometry(QtCore.QRect(0, 10, 141, 121))
        self.label_60.setStyleSheet("image: url(:/newPrefix/buttermilk-fried-chicken-12-square.jpg);")
        self.label_60.setText("")
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.frame_9)
        self.label_61.setGeometry(QtCore.QRect(20, 140, 101, 16))
        self.label_61.setStyleSheet("font: 12pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.frame_9)
        self.label_62.setGeometry(QtCore.QRect(20, 160, 101, 16))
        self.label_62.setStyleSheet("font: 10pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.label_62.setAlignment(QtCore.Qt.AlignCenter)
        self.label_62.setObjectName("label_62")
        self.addWings = QtWidgets.QPushButton(self.frame_9)
        self.addWings.setGeometry(QtCore.QRect(70, 190, 61, 31))
        self.addWings.setStyleSheet("background-color: rgb(220, 166, 88);\n"
"font: 75 12pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.addWings.setObjectName("addWings")
        self.amountWings = QtWidgets.QLineEdit(self.frame_9)
        self.amountWings.setGeometry(QtCore.QRect(10, 190, 51, 31))
        self.amountWings.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"Calibri\";\n"
"border-radius: 15px;")
        self.amountWings.setText("")
        self.amountWings.setAlignment(QtCore.Qt.AlignCenter)
        self.amountWings.setObjectName("amountWings")
        self.profile = QtWidgets.QPushButton(self.frame_10)
        self.profile.setGeometry(QtCore.QRect(610, 20, 51, 51))
        self.profile.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"\n"
"\n"
"")
        self.profile.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Pictures/New/icons8_male_user_60px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profile.setIcon(icon6)
        self.profile.setIconSize(QtCore.QSize(120, 120))
        self.profile.setObjectName("profile")
        FoodMenuwindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(FoodMenuwindow)
        self.statusbar.setObjectName("statusbar")
        FoodMenuwindow.setStatusBar(self.statusbar)

        self.addQabuli.pressed.connect(self.addQabuliToCart)
        self.addBiryani.pressed.connect(self.addBiryaniToCart)
        self.addRice.pressed.connect(self.addRiceToCart)
        self.addKebab.pressed.connect(self.addKebabToCart)
        self.addQorma.pressed.connect(self.addQormaToCart)
        self.addMeat.pressed.connect(self.addMeatBallsToCart)
        self.addSpag.pressed.connect(self.addSpagToCart)
        self.addWings.pressed.connect(self.addWingsToCart)

        self.cartbtn.pressed.connect(self.openCart)
        self.drinksbtn.pressed.connect(self.openDrinks)
        self.extrasBtn.pressed.connect(self.openExtras)

        self.retranslateUi(FoodMenuwindow)
        QtCore.QMetaObject.connectSlotsByName(FoodMenuwindow)

    def addQabuliToCart(self):
        name = self.label_31.text()
        price = 120
        amount = int(self.amountQabuli.text())
        conn = sqlite3.connect("restaurant.db", isolation_level=None)
        cursor = conn.cursor()
        total = amount * price
        taxed_total = total + (total * 0.06)

        cursor.execute(
            "INSERT INTO `cart` (item_name, quantity, price, total, taxed_total) VALUES (?, ?, ?, ?, ?)",
            (name, str(amount), str(price), str(total), str(taxed_total)))
        conn.commit()

    def addBiryaniToCart(self):
        name = self.label_40.text()
        price = 120
        amount = int(self.amountBiryani.text())
        conn = sqlite3.connect("restaurant.db", isolation_level=None)
        cursor = conn.cursor()
        total = amount * price
        taxed_total = total + (total * 0.06)

        cursor.execute(
            "INSERT INTO `cart` (item_name, quantity, price, total, taxed_total) VALUES (?, ?, ?, ?, ?)",
            (name, str(amount), str(price), str(total), str(taxed_total)))
        conn.commit()

    def addRiceToCart(self):
        name = self.label_43.text()
        price = 100
        amount = int(self.amountRice.text())
        conn = sqlite3.connect("restaurant.db", isolation_level=None)
        cursor = conn.cursor()
        total = amount * price
        taxed_total = total + (total * 0.06)

        cursor.execute(
            "INSERT INTO `cart` (item_name, quantity, price, total, taxed_total) VALUES (?, ?, ?, ?, ?)",
            (name, str(amount), str(price), str(total), str(taxed_total)))
        conn.commit()

    def addKebabToCart(self):
        name = self.label_49.text()
        price = 180
        amount = int(self.amountKebab.text())
        conn = sqlite3.connect("restaurant.db", isolation_level=None)
        cursor = conn.cursor()
        total = amount * price
        taxed_total = total + (total * 0.06)

        cursor.execute(
            "INSERT INTO `cart` (item_name, quantity, price, total, taxed_total) VALUES (?, ?, ?, ?, ?)",
            (name, str(amount), str(price), str(total), str(taxed_total)))
        conn.commit()

    def addQormaToCart(self):
        name = self.label_52.text()
        price = 140
        amount = int(self.amountQorma.text())
        conn = sqlite3.connect("restaurant.db", isolation_level=None)
        cursor = conn.cursor()
        total = amount * price
        taxed_total = total + (total * 0.06)

        cursor.execute(
            "INSERT INTO `cart` (item_name, quantity, price, total, taxed_total) VALUES (?, ?, ?, ?, ?)",
            (name, str(amount), str(price), str(total), str(taxed_total)))
        conn.commit()

    def addMeatBallsToCart(self):
        name = self.label_55.text()
        price = 130
        amount = int(self.amountMeat.text())
        conn = sqlite3.connect("restaurant.db", isolation_level=None)
        cursor = conn.cursor()
        total = amount * price
        taxed_total = total + (total * 0.06)

        cursor.execute(
            "INSERT INTO `cart` (item_name, quantity, price, total, taxed_total) VALUES (?, ?, ?, ?, ?)",
            (name, str(amount), str(price), str(total), str(taxed_total)))
        conn.commit()

    def addSpagToCart(self):
        name = self.label_58.text()
        price = 140
        amount = int(self.amountSpag.text())
        conn = sqlite3.connect("restaurant.db", isolation_level=None)
        cursor = conn.cursor()
        total = amount * price
        taxed_total = total + (total * 0.06)

        cursor.execute(
            "INSERT INTO `cart` (item_name, quantity, price, total, taxed_total) VALUES (?, ?, ?, ?, ?)",
            (name, str(amount), str(price), str(total), str(taxed_total)))
        conn.commit()

    def addWingsToCart(self):
        name = self.label_61.text()
        price = 160
        amount = int(self.amountWings.text())
        conn = sqlite3.connect("restaurant.db", isolation_level=None)
        cursor = conn.cursor()
        total = amount * price
        taxed_total = total + (total * 0.06)

        cursor.execute(
            "INSERT INTO `cart` (item_name, quantity, price, total, taxed_total) VALUES (?, ?, ?, ?, ?)",
            (name, str(amount), str(price), str(total), str(taxed_total)))
        conn.commit()

    def retranslateUi(self, FoodMenuwindow):
        _translate = QtCore.QCoreApplication.translate
        FoodMenuwindow.setWindowTitle(_translate("FoodMenuwindow", "Food Menu"))
        self.drinksbtn.setText(_translate("FoodMenuwindow", "Drinks"))
        self.extrasBtn.setText(_translate("FoodMenuwindow", "Extras"))
        self.cartbtn.setText(_translate("FoodMenuwindow", "Cart"))
        self.homebtn.setText(_translate("FoodMenuwindow", "Home"))
        self.profile2.setText(_translate("FoodMenuwindow", "Profile"))
        self.logoutbtn.setText(_translate("FoodMenuwindow", "Log out"))
        self.label_3.setText(_translate("FoodMenuwindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Food Menu</span></p></body></html>"))
        self.user.setText(_translate("FoodMenuwindow", self.emailtxt))
        self.label_31.setText(_translate("FoodMenuwindow", "Qabuli Palaw"))
        self.label_32.setText(_translate("FoodMenuwindow", "120 AFS"))
        self.addQabuli.setText(_translate("FoodMenuwindow", "Add"))
        self.amountQabuli.setPlaceholderText(_translate("FoodMenuwindow", "Amount"))
        self.label_40.setText(_translate("FoodMenuwindow", "Biryani"))
        self.label_41.setText(_translate("FoodMenuwindow", "120 AFS"))
        self.addBiryani.setText(_translate("FoodMenuwindow", "Add"))
        self.amountBiryani.setPlaceholderText(_translate("FoodMenuwindow", "Amount"))
        self.label_43.setText(_translate("FoodMenuwindow", "White Rice"))
        self.label_44.setText(_translate("FoodMenuwindow", "100 AFS"))
        self.addRice.setText(_translate("FoodMenuwindow", "Add"))
        self.amountRice.setPlaceholderText(_translate("FoodMenuwindow", "Amount"))
        self.label_49.setText(_translate("FoodMenuwindow", "Chicken Kebab"))
        self.label_50.setText(_translate("FoodMenuwindow", "180 AFS"))
        self.addKebab.setText(_translate("FoodMenuwindow", "Add"))
        self.amountKebab.setPlaceholderText(_translate("FoodMenuwindow", "Amount"))
        self.label_52.setText(_translate("FoodMenuwindow", "Meat Qorma"))
        self.label_53.setText(_translate("FoodMenuwindow", "140 AFS"))
        self.addQorma.setText(_translate("FoodMenuwindow", "Add"))
        self.amountQorma.setPlaceholderText(_translate("FoodMenuwindow", "Amount"))
        self.label_55.setText(_translate("FoodMenuwindow", "Meat Balls"))
        self.label_56.setText(_translate("FoodMenuwindow", "130 AFS"))
        self.addMeat.setText(_translate("FoodMenuwindow", "Add"))
        self.amountMeat.setPlaceholderText(_translate("FoodMenuwindow", "Amount"))
        self.label_58.setText(_translate("FoodMenuwindow", "Spaghetti"))
        self.label_59.setText(_translate("FoodMenuwindow", "140 AFS"))
        self.addSpag.setText(_translate("FoodMenuwindow", "Add"))
        self.amountSpag.setPlaceholderText(_translate("FoodMenuwindow", "Amount"))
        self.label_61.setText(_translate("FoodMenuwindow", "Chicken Wings"))
        self.label_62.setText(_translate("FoodMenuwindow", "160 AFS"))
        self.addWings.setText(_translate("FoodMenuwindow", "Add"))
        self.amountWings.setPlaceholderText(_translate("FoodMenuwindow", "Amount"))
import images


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FoodMenuwindow = QtWidgets.QMainWindow()
    ui = Ui_FoodMenuwindow(window="", email="")
    ui.setupUi(FoodMenuwindow)
    FoodMenuwindow.show()
    sys.exit(app.exec_())
