# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'orderList.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sqlite3

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_orderList(object):
    def __init__(self, window):
        self.window = QtWidgets.QMainWindow()

    def openLogin(self):
        from login import Ui_loginPage
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_loginPage(window="")
        self.ui.setupUi(self.window)
        self.window.show()
        orderList.close()

    def openAdmin(self):
        # self.exit_login()
        from admin import Ui_OrderDetails
        self.window = QtWidgets.QWidget()
        self.ui = Ui_OrderDetails(window="")
        self.ui.setupUi(self.window)
        self.window.show()
        orderList.close()

    def setupUi(self, orderList):
        orderList.setObjectName("orderList")
        orderList.resize(900, 650)
        self.centralwidget = QtWidgets.QWidget(orderList)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_14 = QtWidgets.QFrame(self.centralwidget)
        self.frame_14.setGeometry(QtCore.QRect(0, 0, 170, 700))
        self.frame_14.setStyleSheet("background-color: rgb(51, 55, 53);")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.drinksbtn_4 = QtWidgets.QPushButton(self.frame_14)
        self.drinksbtn_4.setGeometry(QtCore.QRect(10, 220, 151, 31))
        self.drinksbtn_4.setStyleSheet("background-color: rgb(154, 154, 154);\n"
"font: 75 14pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Pictures/New/icons8_details_24px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.drinksbtn_4.setIcon(icon)
        self.drinksbtn_4.setIconSize(QtCore.QSize(20, 20))
        self.drinksbtn_4.setObjectName("drinksbtn_4")
        self.homebtn_4 = QtWidgets.QPushButton(self.frame_14)
        self.homebtn_4.setGeometry(QtCore.QRect(10, 180, 151, 31))
        self.homebtn_4.setStyleSheet("background-color: rgb(154, 154, 154);\n"
"font: 75 14pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius: 15px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Pictures/New/icons8_combo_chart_24px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homebtn_4.setIcon(icon1)
        self.homebtn_4.setIconSize(QtCore.QSize(20, 20))
        self.homebtn_4.setObjectName("homebtn_4")
        self.profile2_6 = QtWidgets.QPushButton(self.frame_14)
        self.profile2_6.setGeometry(QtCore.QRect(10, 540, 151, 31))
        self.profile2_6.setStyleSheet("background-color: rgb(154, 154, 154);\n"
"font: 75 14pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Pictures/New/icons8_user_male_24px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profile2_6.setIcon(icon2)
        self.profile2_6.setIconSize(QtCore.QSize(20, 20))
        self.profile2_6.setObjectName("profile2_6")
        self.logoutbtn_4 = QtWidgets.QPushButton(self.frame_14)
        self.logoutbtn_4.setGeometry(QtCore.QRect(10, 580, 151, 31))
        self.logoutbtn_4.setStyleSheet("background-color: rgb(154, 154, 154);\n"
"font: 75 14pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Pictures/New/icons8_logout_rounded_left_24px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logoutbtn_4.setIcon(icon3)
        self.logoutbtn_4.setIconSize(QtCore.QSize(20, 20))
        self.logoutbtn_4.setObjectName("logoutbtn_4")
        self.label_39 = QtWidgets.QLabel(self.frame_14)
        self.label_39.setGeometry(QtCore.QRect(30, 30, 111, 101))
        self.label_39.setStyleSheet("border-radius: 50px;\n"
"\n"
"")
        self.label_39.setText("")
        self.label_39.setPixmap(QtGui.QPixmap("Pictures/New/circle-cropped.png"))
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.frame_15 = QtWidgets.QFrame(self.centralwidget)
        self.frame_15.setGeometry(QtCore.QRect(180, 10, 711, 641))
        self.frame_15.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label_40 = QtWidgets.QLabel(self.frame_15)
        self.label_40.setGeometry(QtCore.QRect(260, -30, 191, 191))
        self.label_40.setText("")
        self.label_40.setPixmap(QtGui.QPixmap("Pictures/New/Logo.png"))
        self.label_40.setScaledContents(True)
        self.label_40.setObjectName("label_40")
        self.label_6 = QtWidgets.QLabel(self.frame_15)
        self.label_6.setGeometry(QtCore.QRect(310, 100, 91, 31))
        self.label_6.setStyleSheet("font: 75 20pt \"Arial\";\n"
"color: rgb(198, 156, 109);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.user_4 = QtWidgets.QLabel(self.frame_15)
        self.user_4.setGeometry(QtCore.QRect(600, 80, 61, 31))
        self.user_4.setStyleSheet("font: 75 12pt \"Arial\";\n"
"color: rgb(198, 156, 109);")
        self.user_4.setAlignment(QtCore.Qt.AlignCenter)
        self.user_4.setObjectName("user_4")
        self.frame_21 = QtWidgets.QFrame(self.frame_15)
        self.frame_21.setGeometry(QtCore.QRect(10, 140, 691, 471))
        self.frame_21.setStyleSheet("background-color: rgb(51, 55, 53);\n"
"broder-radius: 25px;")
        self.frame_21.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setLineWidth(3)
        self.frame_21.setObjectName("frame_21")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame_21)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 10, 671, 451))
        self.tableWidget_2.setStyleSheet("font: 10pt \"Arial\";\n"
"background-color: rgb(255, 255, 255);")
        self.tableWidget_2.setRowCount(100)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        self.tableWidget_2.setColumnWidth(0, 155)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        self.tableWidget_2.setColumnWidth(1, 155)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        self.tableWidget_2.setColumnWidth(2, 155)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.tableWidget_2.setColumnWidth(3, 155)
        self.profile_4 = QtWidgets.QPushButton(self.frame_15)
        self.profile_4.setGeometry(QtCore.QRect(610, 20, 51, 51))
        self.profile_4.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"\n"
"\n"
"")
        self.profile_4.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Pictures/New/icons8_male_user_60px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profile_4.setIcon(icon4)
        self.profile_4.setIconSize(QtCore.QSize(120, 120))
        self.profile_4.setObjectName("profile_4")
        self.showOrderBtn = QtWidgets.QPushButton(self.frame_15)
        self.showOrderBtn.setGeometry(QtCore.QRect(20, 100, 151, 31))
        self.showOrderBtn.setStyleSheet("background-color: rgb(154, 154, 154);\n"
"font: 75 14pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Pictures/New/icons8_eye_24px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.showOrderBtn.setIcon(icon5)
        self.showOrderBtn.setIconSize(QtCore.QSize(20, 20))
        self.showOrderBtn.setObjectName("showOrderBtn")
        orderList.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(orderList)
        self.statusbar.setObjectName("statusbar")
        orderList.setStatusBar(self.statusbar)

        self.DisplayData()
        self.homebtn_4.pressed.connect(self.openAdmin)
        self.showOrderBtn.pressed.connect(self.showClickedOrder)
        self.logoutbtn_4.pressed.connect(self.logout)

        self.retranslateUi(orderList)
        QtCore.QMetaObject.connectSlotsByName(orderList)

    def logout(self):
        msg = QMessageBox()
        msg.setWindowTitle("Info")
        msg.setText("You have been logged out!")
        msg.setIcon(QMessageBox.Information)
        x = msg.exec_()
        self.openLogin()

    def DisplayData(self):
        global conn, cursor
        conn = sqlite3.connect("restaurant.db", isolation_level=None)
        cursor = conn.cursor()
        query = "SELECT * FROM orders"

        tableRow = 0
        for row in cursor.execute(query):
            self.tableWidget_2.setItem(tableRow, 0, QtWidgets.QTableWidgetItem(row[1]))
            self.tableWidget_2.setItem(tableRow, 1, QtWidgets.QTableWidgetItem(row[2]))
            self.tableWidget_2.setItem(tableRow, 2, QtWidgets.QTableWidgetItem(row[3]))
            self.tableWidget_2.setItem(tableRow, 3, QtWidgets.QTableWidgetItem(row[4]))
            tableRow += 1
        cursor.close()
        conn.close()

    def showClickedOrder(self):
        rowTable = self.tableWidget_2.currentRow()
        print(rowTable)

        conn = sqlite3.connect("restaurant.db", isolation_level=None)
        cursor = conn.cursor()
        if rowTable > -1:
            item_name = str(self.tableWidget_2.item(rowTable, 1).text())

            sql_update_query = "SELECT * FROM orders"
            cursor.execute(sql_update_query)

            items = []
            for row in cursor.execute(sql_update_query):
                items.append(row[1])
            item = str(items[rowTable])
            print(item)

            query = "SELECT * FROM orders where items = " + item_name + ""
            cursor.execute(query)
            data = cursor.fetchone()
            print(data)

            conn.commit()
            cursor.close()
            conn.close()

    def retranslateUi(self, orderList):
        _translate = QtCore.QCoreApplication.translate
        orderList.setWindowTitle(_translate("orderList", "MainWindow"))
        self.drinksbtn_4.setText(_translate("orderList", "Order Details"))
        self.homebtn_4.setText(_translate("orderList", "Dashboard"))
        self.profile2_6.setText(_translate("orderList", "Profile"))
        self.logoutbtn_4.setText(_translate("orderList", "Log out"))
        self.label_6.setText(_translate("orderList", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Food Menu</span></p></body></html>"))
        self.user_4.setText(_translate("orderList", "Admin"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("orderList", "Items"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("orderList", "Total"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("orderList", "Net Profit"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("orderList", "Date"))
        self.showOrderBtn.setText(_translate("orderList", "Show Order"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    orderList = QtWidgets.QMainWindow()
    ui = Ui_orderList(window="")
    ui.setupUi(orderList)
    orderList.show()
    sys.exit(app.exec_())
